# -*- coding: utf-8 -*-
"""EDA and Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ozDSnIi17_KfKE_vnVeU5NZbcqbcyd6F
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/diabetes (2).csv")

df=pd.read_csv("/content/diabetes (2).csv")

df

df.head(10)

df.tail(10)

df.shape[0]

df.shape

df.shape[1]

df.info()

df.describe()

df.isnull().sum()

X=20,3,7,21,17,53,2
plt.plot(X)
plt.show()

y=df["BMI"]
plt.plot(y)

x=df["BMI"]
y=df["Age"]
plt.scatter(x,y)

plt.bar(x,y)

plt.hist(df)

plt.hist(df["BMI"])

plt.hist(df["Glucose"])

plt.hist(df["Insulin"])

fig,(ax1,ax2)=plt.subplots(3,3, figsize=(12,10))
ax1.hist(df["Insulin"])
ax2.hist(df["Age"])

fig,(ax)=plt.subplots(figsize=(12,10))
ax.hist(df['Insulin'])
ax.hist(df['Age'])
ax.hist(df['BMI'])
ax.hist(df['BloodPressure'])
ax.hist(df['DiabetesPedigreeFunction'])
ax.hist(df['Glucose'])

cols=df.columns.tolist()

for i in range(len(cols)):
  plt.subplot(3,3,i+1)
  plt.plot(df[cols[i]])

plt.pie(df['SkinThickness'])

plt.pie(df['Outcome'])

sns.lineplot(df["Age"])

sns.scatterplot(x='Age',y='Pregnancies',data=df )

sns.scatterplot(df['SkinThickness'])

sns.scatterplot(df['BloodPressure'])

sns.barplot(df['Insulin'])

sns.displot(df['BMI'])

sns.distplot(df['Glucose'])

sns.pairplot(df)

sns.pairplot(df,hue='Outcome')